import type { Metadata } from "next";

import { ibmPlexMono } from "@/lib";
import "@/styles/globals.css";
import AuthContextProvider from "@/contexts/authContext";

export const metadata: Metadata = {
	title: "Ensaware",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="es">
			<body className={`${ibmPlexMono.className} antialiased`}>
				<AuthContextProvider>{children}</AuthContextProvider>
			</body>
		</html>
	);
}
