import type { Metadata } from "next";

import { ibmPlexMono } from "@/lib";
import "@/styles/globals.css";

export const metadata: Metadata = {
	title: "Ensaware",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="es">
			<body className={`${ibmPlexMono.className} antialiased`}>{children}</body>
		</html>
	);
}
